spring:
  datasource:
    url: jdbc:postgresql://mouse.db.elephantsql.com/fksqyoke
    username: fksqyoke
    password: 0039NNBG6fAxs5lgihc1OG-xfR30D42t
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect